# Generated by Django 5.0.6 on 2024-07-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='num_consult',
        ),
        migrations.AddField(
            model_name='examen',
            name='diagnostic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
